#Colab Environment code, Do not run locally!!

# !pip install edge_tts pydub nest_asyncio

import os
import re
import csv
import random
import asyncio
import numpy as np
import shutil
import time # Import time for sleep
# import nest_asyncio
# nest_asyncio.apply()

from datasets import Dataset, Audio
from transformers import AutoProcessor
import edge_tts
from pydub import AudioSegment

# ========================================================
# STEP 1: RAW TEXT (800 lines - Bilingual Feedback Focusing)
# ========================================================

texts = [
    "barang ni quality tapi delivery dia slow sikit",
    "customer service okay cuma staff kurang friendly",
    "quality dia tak elok and price dia too expensive",
    "i suka bungkusan dia but barang sampai pecah",
    "feedback dari support team fast tapi tak help sangat",
    "price murah tapi performance dia bit sluggish",
    "everything okay cuma delivery tu lambat sangat",
    "customer service very helpful and fast reply",
    "app ni selalu crash, susah i nak guna",
    "barang sampai cepat tapi bungkusan dia kurang kemas",
    "barang ni bermutu tinggi and tahan lama, i puas hati",
    "service bit slow tapi masih boleh diterima",
    "i not satisfied directly with quality this time",
    "barang ni look good tapi function dia tak okay",
    "fast delivery and barang safe, terbaik",
    "customer support tak reply and slow bagi answer",
    "price dia bit expensive tapi worth it sebab quality",
    "barang arrived damaged and refund process slow",
    "easy to use tapi app ni got many technical issues",
    "design memang cantik tapi performance less satisfying",
    "overall experience very satisfying and smooth",
    "really not worth the price and quality very low",
    "fast delivery tapi got missing items",
    "staff dia very friendly and help me a lot tadi",
    "barang ni macam tak durable and fast sangat rosak",
    "quality bagus tapi delivery dia too slow",
    "app ni very helpful and easy to use",
    "customer service less satisfying and slow feedback",
    "price okay dah tapi packaging dia teruk sangat ni",
    "barang arrived damaged, i very disappointed",
    "service fast and efficient tapi price bit high",
    "don't recommend directly sebab quality low sangat",
    "easy installation tapi manual dia less clear",
    "barang ni surely good and worth to buy",
    "delivery very slow and i tired waiting",
    "staff tak friendly directly and service indeed bad",
    "performance good tapi phone ni fast jadi hot",
    "barang ni okay cuma got minor damage kat tepi",
    "support team very helpful and fast reply",
    "always slow and no news from them",
    "barang tak macam in picture and very disappointing",
    "quality good tapi price offered too high",
    "app ni always crash and menyusahkan i nak guna",
    "staff very helpful and all friendly",
    "barang ni macam not functioning correctly, i stuck",
    "fast delivery tapi packaging arrived lunyai",
    "everything not disappointing but can improve more",
    "customer service slow and not helpful directly tadi",
    "barang ni very high quality and i recommend to all",
    "refund process very slow and complicated",
    "easy to use and app ni very user friendly",
    "barang arrived slow and got damage pula, i angry",
    "quality ordinary saja tapi okay for the price",
    "service good dah tapi feedback dia slow sikit",
    "barang ni fast sangat rosak and not durable",
    "very satisfied with service and quality given",
    "app hard to use and got too many problems",
    "staff not professional at all and very rude tadi",
    "delivery fast and reliable, never disappointing",
    "barang tak macam expected and i feel disappointed",
    "price worth it cuma delivery dia too slow sikit",
    "customer support not helpful directly, waste time",
    "barang ni indeed the best and i very satisfied",
    "service less good and slow bagi feedback",
    "quality low tapi price given very expensive",
    "barang arrived fast and packed very neatly",
    "app very slow and always stuck, tired using",
    "staff friendly cuma less efficient",
    "overall experience bad and i don't recommend at all",
    "barang ni okay saja to use every day",
    "delivery bit slow tapi barang dia indeed great",
    "customer service fast and helpful, indeed the best",
    "quality not satisfying and very disappointing",
    "barang ni very good and reliable, jimat",
    "service bit slow tapi i still can accept lagi",
    "barang damaged masa arrived and i feel very sad",
    "easy installation but performance dia bit low sikit",
    "workers very good and all professional",
    "fast delivery tapi sent the wrong item pula",
    "product ni average saja and nothing special pun",
    "very good quality and item ni really durable",
    "service was very poor and i tak recommend langsung",
    "app ni good but need more improvements lagi",
    "customer support bit slow tapi helpful juga",
    "item ni bit expensive tapi worth it for the quality",
    "very fast delivery and indeed efficient",
    "low quality and item ni broke very fast semalam",
    "staff not very friendly and not helpful at all",
    "item ni okay but seems to have minor issues sikit",
    "overall i satisfied and highly recommend it lah",
    "item ni good tapi delivery person bit rude tadi",
    "i feel waste of money sebab quality is poor sangat",
    "very fast delivery, order morning arrived evening terus",
    "staff kat counter slow and not efficient directly pun",
    "unreasonable price and i never heard of brand ni before",
    "i like feature ni tapi sometimes it get stuck pula",
    "service ni excellent, highly recommended ni",
    "item ni small tapi space inside very tight sangat",
    "i waiting already a month but item hasn't arrived lagi",
    "refund policy strange, please fix immediately",
    "very simple interface and app ni easy to understand",
    "item ni bit heavy tapi indeed very sturdy bagi",
    "excellent service tapi packaging bit thin sikit",
    "want to buy lagi but stock always out memanjang",
    "payment system always got error, very troublesome",
    "seller very quick response and very helpful ni",
    "color dia beza sikit from picture, i feel sad pula",
    "material ni premium tapi stitching bit messy sikit",
    "fast delivery and cheap price, absolutely the best lah",
    "customer service not friendly and very slow semalam",
    "item ni indeed great, mutu dia very high bagi",
    "item missing one part and it is very troublesome",
    "overall okay tapi delivery can be improved further lagi",
    "battery life too short for this price, tak worth it",
    "i bought two but only one functioning properly tadi",
    "best application for giving feedback and ratings ni",
    "delivery person was very helpful and good person tadi",
    "great packaging and safety indeed guaranteed semalam",
    "item ni worth it, i don't regret buy kat sini",
    "seller slow reply and bit disappointing juga ni",
    "easy to install tapi internet connection dia weak",
    "good performance tapi design look bit old school sikit",
    "i very satisfied with this purchase semalam",
    "terrible quality and item broke after two days use",
    "very fast service, indeed impressive tadi",
    "app ni slow, need to fix immediately please ni",
    "staff very knowledgeable and friendly ni",
    "delivery delayed for a week without news, i quite angry",
    "item ni high quality and very comfortable to use semalam",
    "i don't recommend this for older people lah ni",
    "worth the price and quality is okay, quite good",
    "delivery cost too expensive for area sini, not logical",
    "i really love the result, indeed truly great semalam",
    "customer helpline always busy, i tired calling ni",
    "item arrived in wet box, luckily item inside safe semalam",
    "display neat tapi text too small, hurt my eyes sikit",
    "item ni worth buying, believe me lah ni",
    "service just okay tapi got room for improvement lagi",
    "quality just average and color fade a bit fast semalam",
    "tracking number got but no info online directly ni",
    "i disappointed sebab item is not as described tadi",
    "item ni okay tapi delivery was very long sangat semalam",
    "staff busy chatting and ignored me just now, sedihnya",
    "packaging torn masa arrived, not neat at all",
    "very efficient team and fast problem solving ni",
    "price bit high for such a simple item ni bagi",
    "i didn't expect it to work so well, impressed semalam",
    "very early delivery and delivery person very polite tadi",
    "material feels cheap and low quality guna ni",
    "app need update, always getting stuck and very slow ni",
    "item ni durable and very sturdy, i like it ni",
    "refund received tapi process was slow sikit semalam",
    "best level of service, i very happy today ni",
    "quality not as expected, feel bit fragile ni",
    "fast delivery and good communication from seller ni",
    "that discount look fake, price remain same saja ni",
    "i happy with quick delivery yesterday afternoon",
    "item got scratches and look like used item pula",
    "easy to use and very convenient sangat-sangat ni",
    "technical support section very helpful and kind ni",
    "item ni very suitable for my needs, simple saja ni",
    "delivery on time and item in good condition semalam",
    "workers very helpful tapi talk too fast tadi",
    "i got bad experience with branch area sini ni",
    "packaging need to be stronger for fragile items lah",
    "quick response from seller and very polite person semalam",
    "quality is better compared to other fabric brands ni",
    "app frequently stop every time i open it, exhausting",
    "i don't recommend item ni directly, don't buy ni",
    "worth it, cheap price and fast delivery, excellent lah",
    "color options very limited here, not many choices pun",
    "refund process went smoothly and easy, best lah ni",
    "item sampai selamat and dibungkus kemas semalam",
    "item ni memang bagus, kualiti tinggi seller bagi",
    "delivery person baik hati, sanggup tunggu i tadi",
    "service lembap and makanan sejuk, lapar gila tadi",
    "quality control memang kurang kat sini rasanya",
    "i suka design dia tapi warna nampak kusam sikit",
    "tracking system tak accurate and pening semalam",
    "geram gila dengan service yang slow tadi",
    "pembelian yang berbaloi, takda complaint and puas hati",
    "barang ni sebenarnya kecik, dalam gambar nampak besar",
    "staff kena training lagi pasal info product ni",
    "delivery laju tapi kos dia mahal sangat bagi i",
    "quality biasa je tapi nampak ada kesan gam kat situ",
    "i suka function ni, memang baru and menarik gila",
    "after sales service macam tak wujud je kat sini",
    "barang pack elok and sampai awal dah semalam",
    "app ni memang interactive and seronok nak guna",
    "barang ni tak berguna pun, membazir duit je beli",
    "feedback pantas tapi jawapan tak membantu, hampa semalam",
    "delivery slow sikit tapi barang dia padu semalam",
    "customer service sangat bersabar and baik tadi",
    "quality terbaik semalam, memang puas hati sangat ni",
    "display app bersepah and susah nak cari feature",
    "i tak suka courier ni, selalu lambat hantar barang",
    "item sampai betul and on time semalam seller hantar",
    "service memuaskan tapi rasanya boleh improve lagi",
    "material ni selesa and kualiti dia elok, terbaik lah",
    "takda update tracking langsung sampailah barang sampai rumah",
    "i puas hati gila dengan service yang mantap",
    "packaging dia susah nak bukak, kecewa sikit i",
    "memang professional and delivery pantas, terbaik",
    "barang murah tapi macam takda kualiti langsung ni",
    "staff tak beradab and taknak tolong i tadi",
    "delivery ambik masa dua minggu untuk order local, slow",
    "i suka sangat design ni, nampak lawa gila",
    "item ni takda manual, macam mana nak guna ni?",
    "customer support memang padu and cepat bagi settle",
    "app ni banyak bug kat android, tolong fix secepatnya",
    "barang ni tahan lasak and bagus guna outdoor",
    "delivery slow sikit tapi overall okay je lah",
    "quality memang elok untuk harga ni, murah pun murah",
    "i tak happy langsung dengan update app baru-baru ni",
    "dapat separuh je refund, kenapa macam tu eh?",
    "barang sampai lambat and kotak kemek teruk semalam",
    "senang nak faham and instruction dalam app ni jelas",
    "staff ramah tapi nampak kalut sikit tadi",
    "delivery laju gila, paling laju i pernah tengok",
    "barang original and berfungsi dengan cemerlang, terbaik lah",
    "chat support tu sebenarnya robot, patutlah kaku sangat",
    "quality agak kurang and jahitan dia banyak longgar",
    "i recommend seller ni, memang boleh dipercayai sangat",
    "abang delivery call dulu sebelum sampai, bagus adabnya",
    "service kurang memuaskan and ambik masa lama semalam",
    "barang sebijik macam dalam gambar, cantik sangat lah",
    "display app kemas tapi ads dia menyemak gila",
    "item ni kecik and sangat senang nak bawak ke mana-mana",
    "delivery laju tapi barang tinggal kat pagar je tadi",
    "quality teruk gila and material nipis, menyesal beli semalam",
    "staff peramah and buat kerja laju tadi",
    "ada masalah sikit masa bayar tadi, system interrupted lagi",
    "barang dilindungi sangat baik dalam packaging semalam",
    "i rasa happy gila order dari kedai ni, terbaik lah",
    "barang okay tapi bateri cepat gila habis semalam",
    "customer support tak membantu and slow gila reply tadi",
    "delivery laju walaupun order dari luar negara semalam",
    "quality just okay tapi i expected lebih dari ni",
    "app asyik hang je masa i tengah tulis feedback semalam",
    "item ni memang berkualiti tinggi, tak ragu lagi",
    "delivery slow sikit tapi harga dia sangat berpatutan",
    "delivery person tak sabar langsung masa hantar tadi",
    "service cepat tapi ada silap sikit masa pack barang",
    "barang hilang satu part kecik, sedih gila i rasa",
    "kualiti elok and harga mampu milik, memang terbaik",
    "icon app nampak tak menarik tapi dalam dia okay je",
    "i rasa refund process ni rumit sangat lah",
    "barang sampai dalam tiga hari, kira laju jugak tu",
    "material berkualiti tinggi, nanti nak order lagi lah",
    "staff sangat membantu tapi kedai sesak tadi",
    "semua instruction dalam bahasa asing, payah nak faham",
    "barang tak function masa sampai, membazir duit je",
    "respon laju and support team memang mantap",
    "item ni ringan and senang nak angkut ke sana sini",
    "delivery slow sikit tapi customer service membantu semalam",
    "kualiti premium tapi handle dia longgar sikit lah",
    "i suka packaging ni, nampak mesra alam sangat",
    "company delivery ni memang boleh diharap kat area i",
    "service laju and semua pekerja sangat sopan tadi",
    "app display nampak modern and kemas gila semalam",
    "barang beza sikit dari description, agak kecewa lah",
    "delivery laju tapi barang salah sampai semalam",
    "customer service settlekan masalah i laju je tadi",
    "kualiti luar biasa, susah nak cari item macam ni",
    "app ni banyak bug lepas update baru-baru ni",
    "item ni memuaskan and praktikal untuk guna harian",
    "delivery laju and harga pun murah, jimat banyak",
    "seller biadap gila masa i tanya soalan dekat chat",
    "barang pack kemas and sampai awal, terbaik lah",
    "quality suam-suam kuku je and nampak tak exclusive",
    "pekerja professional and beradab sangat tadi tu",
    "app design sangat simple, i suka nampak clean je",
    "delivery slow tapi abang hantar tu baik sangat orangnya",
    "quality hancur gila and barang cepat sangat rosak",
    "respon pantas and komunikasi sangat jelas",
    "item ni kecik tapi function dia power gila",
    "kos hantar mahal sangat untuk barang kecik macam ni",
    "i rasa barang ni worth the price, puas hati gila",
    "service memang mantap and pekerja buat kerja laju",
    "quality teruk gila and nampak macam barang fake je",
    "delivery paling laju dalam bandar ni, good job",
    "customer service kat sini selalu bantu, seronok gila",
    "barang pecah sebab packaging bersepah masa delivery tadi",
    "senang nak guna and sangat berkesan i pakai ni",
    "app ni buat phone i hang, tolong fix please",
    "highly recommended untuk kualiti and kelajuan, terbaik",
    "barang nampak kecik kalau nak banding dengan gambar",
    "pekerja kat branch ni memang sangat membantu lah",
    "delivery sangat smooth and takda masalah langsung tadi",
    "quality okay dah tapi bau kuat sikit, pening kepala i",
    "i memang suka gila feature baru ni, memang terbaik",
    "proses refund ambik masa lama nak masuk akaun bank",
    "barang sampai awal and dalam keadaan sangat baik",
    "service laju tapi pekerja patut banyakkan senyum",
    "kualiti barang kat sini tak stabil, kena check betul-betul",
    "interface app senang tapi warna dia terang sangat",
    "memang puas hati dengan overall service kat sini, best",
    "abang delivery tak call and terus tinggal macam tu je",
    "quality memang padu and barang nampak mewah gila",
    "delivery laju gila walaupun hari ni cuti bank",
    "barang ada damage and i kena hantar balik tadi",
    "service lembap tapi pekerja dorang baik-baik belaka",
    "barang okay tapi harga boleh kurang lagi sikit lah",
    "customer experience kat sini kurang syok, frust i",
    "senang nak install and terus berfungsi dengan baik semalam",
    "abang delivery ramah sangat and memang on time",
    "janji boleh guna untuk buat kerja, kualiti basic pun okay",
    "i frust gila dengan reply yang lembap ni",
    "barang pack kemas tapi delivery delay sikit semalam",
    "delivery paling laju i pernah rasa setakat ni, terbaik",
    "barang elok tapi buku manual takda tadi, macam mana?",
    "support team sangat sabar melayan i, terima kasih",
    "quality memang elok walaupun harga murah gila",
    "app asyik tulis takda internet, pening i dibuatnya",
    "delivery memang efficient and packaging pun sangat elok",
    "seller ni lembap sikit nak reply message tadi tu",
    "barang sampai hari ni and dalam keadaan yang sangat perfect",
    "service serta-merta and professional setiap masa, terbaik",
    "quality control boleh improve lagi untuk barang macam ni",
    "i suka update apps baru ni, memang smooth gila",
    "delivery laju gila, i terkejut kejap tadi hantar",
    "barang okay cuma nampak macam model lama sikit",
    "customer support memang sangat membantu and ramah",
    "quality konsisten and boleh diharap, memang terbaik",
    "proses hantar sangat telus and i suka cara dorang",
    "barang sampai hari ni and berfungsi dengan cemerlang",
    "delivery pantas, i suggest beli dengan seller ni",
    "app lembap masa nak upload gambar tadi, penat i",
    "quality biasa-biasa and finishing dia kasar sikit",
    "pekerja memang mantap and tahu pasal product yang dijual",
    "parcel tinggal kat jiran, okay lah dari hilang terus",
    "barang sebijik macam description, tak menipu langsung",
    "feedback laju and after sales pun mantap",
    "barang ni bagus, sangat memudahkan kerja i sehari-hari",
    "abang hantar barang sangat sopan and membantu tadi",
    "quality okay tapi harga macam dah naik sikit",
    "i rasa berbaloi beli benda ni, kualiti memang padu",
    "refund settle laju lepas i buat aduan semalam",
    "barang sampai selamat and dibungkus kemas sangat",
    "feedback pantas dari team customer support tadi",
    "barang luar jangkaan i, memang kualiti terbaik lah",
    "service bagus and delivery pun memang laju gila",
    "app senang nak guna terutama part cari item tu",
    "team memang professional and kualiti barang mantap",
    "service delivery kali ni memang laju, terbaik",
    "barang ni berkualiti tapi delivery dia slow sikit",
    "customer service okay cuma staff kurang ramah",
    "kualiti dia tak elok and harga dia mahal sangat",
    "i suka bungkusan dia tapi barang sampai pecah",
    "feedback dari support team laju tapi tak membantu sangat",
    "harga murah tapi performance dia lembap sikit",
    "semua okay cuma delivery tu lambat sangat tadi",
    "customer service sangat membantu and respon laju",
    "app ni selalu crash, susah i nak guna semalam",
    "barang sampai cepat tapi bungkusan dia kurang kemas",
    "barang ni bermutu tinggi and tahan lama, i puas hati",
    "service lambat sikit tapi masih boleh diterima lah",
    "i tak puas hati dengan kualiti barang kali ni",
    "barang ni nampak cantik tapi function dia tak okay",
    "delivery laju and barang selamat sampai, terbaik",
    "customer support tak reply and lambat bagi jawapan",
    "harga dia mahal sikit tapi berbaloi sebab kualiti",
    "barang sampai rosak and proses refund slow gila",
    "senang nak guna tapi app ni banyak masalah teknikal",
    "design memang cantik tapi performance kurang memuaskan",
    "overall experience sangat memuaskan and smooth je",
    "memang tak berbaloi dengan harga, kualiti rendah sangat",
    "delivery laju tapi ada barang yang hilang pula",
    "staff dia peramah sangat and banyak bantu i tadi",
    "barang ni macam tak tahan lama and cepat sangat rosak",
    "kualiti bagus tapi delivery dia lembap sangat",
    "app ni sangat membantu and senang nak guna",
    "customer service kurang memuaskan and respon lambat",
    "harga dah okay tapi packaging dia teruk sangat ni",
    "barang sampai rosak, i kecewa sangat-sangat semalam",
    "service laju and efisien tapi harga mahal sikit",
    "tak recommend langsung sebab kualiti rendah sangat",
    "senang nak pasang tapi manual dia kurang jelas",
    "barang ni memang bagus and berbaloi untuk beli",
    "delivery lembap sangat and i dah letih menunggu",
    "staff tak ramah langsung and service memang teruk",
    "performance bagus tapi phone ni cepat jadi panas",
    "barang ni okay cuma ada kerosakan sikit kat tepi",
    "support team sangat membantu and respon laju gila",
    "selalu lambat and takda khabar berita dari dorang",
    "barang tak macam dalam gambar and sangat mengecewakan",
    "kualiti bagus tapi harga yang ditawarkan mahal sangat",
    "app ni asyik crash and menyusahkan i nak guna",
    "staff sangat membantu and semua peramah belaka",
    "barang ni macam tak berfungsi dengan betul, i pening",
    "delivery laju tapi packaging sampai dalam keadaan lunyai",
    "semuanya okay cuma boleh improve lagi di masa depan",
    "customer service slow and tak membantu langsung tadi",
    "barang ni kualiti tinggi and i recommend kat semua",
    "proses refund sangat lambat and menyusahkan gila",
    "senang nak guna and app ni memang user friendly",
    "barang sampai lambat and ada kerosakan pula, i marah",
    "kualiti biasa-biasa saja tapi okay lah untuk harga tu",
    "service dah elok tapi respon dia lambat sikit",
    "barang ni cepat sangat rosak and tak tahan lasak",
    "sangat puas hati dengan service and kualiti yang diberi",
    "app susah nak guna and ada terlalu banyak masalah",
    "staff tak professional langsung and sangat biadab tadi",
    "delivery laju and boleh dipercayai, tak mengecewakan",
    "barang tak macam yang i bayangkan, rasa hampa sikit",
    "harga berbaloi cuma delivery dia lambat sikit semalam",
    "customer support tak membantu langsung, buang masa i",
    "barang ni memang terbaik and i sangat puas hati",
    "service kurang memuaskan and lambat bagi feedback",
    "kualiti rendah tapi harga yang diberi mahal sangat",
    "barang sampai laju and dibungkus dengan sangat rapi",
    "app lembap sangat and asyik sangkut, letih i guna",
    "staff peramah cuma kurang efisien buat kerja tadi",
    "overall experience teruk and i tak recommend langsung",
    "barang ni okay saja untuk guna harian, takda masalah",
    "delivery lambat sikit tapi barang dia memang mantap",
    "customer service laju and membantu, memang terbaik",
    "kualiti tak memuaskan and sangat mengecewakan i",
    "barang ni sangat bagus and boleh diharap, jimat duit",
    "service lambat sikit tapi i masih boleh sabar lagi",
    "barang rosak masa sampai and i rasa sedih sangat",
    "senang nak pasang tapi performance dia kurang sikit",
    "pekerja sangat bagus and semua professional belaka",
    "delivery laju tapi hantar barang yang salah pula",
    "product ni biasa-biasa saja and takda yang special pun",
    "kualiti memang bagus and barang ni sangat tahan lama",
    "service memang teruk and i tak recommend langsung",
    "app ni bagus cuma perlukan lebih banyak improvement",
    "customer support lambat sikit tapi membantu jugalah",
    "barang ni mahal sikit tapi berbaloi untuk kualitinya",
    "delivery memang laju gila and sangat efisien tadi",
    "kualiti rendah and barang ni pecah cepat sangat semalam",
    "staff tak berapa ramah and tak membantu langsung tadi",
    "barang ni okay cuma nampak macam ada masalah sikit",
    "overall i puas hati and sangat suggest beli kat sini",
    "barang ni bagus cuma abang delivery biadab sikit tadi",
    "i rasa membazir duit sebab kualiti dia teruk sangat",
    "delivery laju gila, order pagi petang dah sampai terus",
    "staff kat kaunter lembap and tak efisien langsung tadi",
    "harga tak masuk akal and i tak pernah dengar brand ni",
    "i suka feature ni tapi kadang-kadang dia sangkut pula",
    "service ni memang cemerlang, sangat recommended",
    "barang ni kecik tapi ruang kat dalam sempit sangat",
    "i dah tunggu sebulan tapi barang tak sampai-sampai lagi",
    "policy refund pelik sangat, tolong fix secepat mungkin",
    "interface sangat simple and app ni senang nak faham",
    "barang ni berat sikit tapi memang sangat kukuh lah",
    "service cemerlang tapi packaging nipis sangat tadi",
    "nak beli lagi tapi stok asyik habis memanjang kat sini",
    "sistem bayaran asyik error, sangat menyusahkan i tadi",
    "seller respon cepat and sangat membantu urusan i",
    "warna dia beza sikit dari gambar, i rasa sedih pula",
    "material ni premium tapi jahitan dia comot sikit lah",
    "delivery laju and harga murah, memang terbaik lah ni",
    "customer service tak ramah and sangat lambat semalam",
    "barang ni memang mantap, mutu dia tinggi sangat bagi i",
    "ada part yang hilang and benda ni sangat menyusahkan",
    "overall okay tapi delivery boleh improve lagi lepas ni",
    "bateri tak tahan lama untuk harga macam ni, tak berbaloi",
    "i beli dua tapi satu saja yang berfungsi dengan betul",
    "app terbaik untuk bagi feedback and rating barang ni",
    "abang delivery sangat membantu and baik orangnya tadi",
    "packaging hebat and keselamatan memang terjamin semalam",
    "barang ni berbaloi, i tak menyesal beli kat kedai ni",
    "seller lambat reply and agak mengecewakan juga ni",
    "senang nak install tapi connection internet dia lemah",
    "performance bagus tapi design nampak lama sikit tadi",
    "i sangat puas hati dengan pembelian kali ni semalam",
    "kualiti teruk and barang pecah lepas dua hari guna",
    "service sangat laju, memang mengagumkan buat kerja",
    "app ni lembap, perlukan fix secepat mungkin please",
    "staff sangat berilmu and peramah orangnya semalam",
    "delivery delay seminggu tanpa berita, i agak marah",
    "barang ni kualiti tinggi and sangat selesa nak guna",
    "i tak recommend benda ni untuk orang tua guna lah",
    "berbaloi dengan harga and kualiti dia okay, cukup baik",
    "kos hantar mahal sangat untuk kawasan sini, tak logik",
    "i suka sangat dengan hasil dia, memang padu gila",
    "customer helpline asyik busy, letih i nak call tadi",
    "barang sampai dalam kotak basah, nasib barang selamat",
    "display kemas tapi tulisan kecik sangat, sakit mata i",
    "barang ni berbaloi beli, percaya lah cakap i ni",
    "service okay saja tapi ada ruang untuk improve lagi",
    "kualiti biasa saja and warna cepat pudar semalam",
    "nombor tracking ada tapi takda info online langsung",
    "i kecewa sebab barang tak macam yang diceritakan",
    "barang ni okay tapi delivery ambik masa lama sangat",
    "staff sibuk sembang and abaikan i tadi, sedihnya rasa",
    "packaging koyak masa sampai, tak kemas langsung lah",
    "team sangat efisien and cepat selesaikan masalah i",
    "harga mahal sikit untuk barang yang simple macam ni",
    "i tak sangka benda ni berfungsi dengan baik, impressed",
    "delivery awal sangat and abang courier sangat sopan",
    "material rasa murah and kualiti rendah guna benda ni",
    "app perlukan update, asyik sangkut and lembap gila",
    "barang ni tahan lasak and sangat kukuh, i suka gila",
    "refund dah dapat tapi proses dia lembap sikit semalam",
    "service tahap terbaik, i sangat happy hari ni guna",
    "kualiti tak macam i jangka, rasa macam rapuh sikit",
    "delivery laju and komunikasi bagus dari seller tadi",
    "discount tu macam tipu je, harga tetap sama saja ni",
    "i gembira dengan penghantaran yang laju petang semalam",
    "barang ada calar and nampak macam barang second hand",
    "senang nak guna and sangat memudahkan urusan i tadi",
    "bahagian technical support sangat membantu and baik",
    "barang ni sangat sesuai dengan keperluan i, simple je",
    "delivery on time and barang dalam keadaan baik semalam",
    "pekerja sangat membantu tapi cakap laju sangat tadi",
    "i ada experience buruk dengan branch kawasan sini ni",
    "packaging kena lebih kuat untuk barang mudah pecah",
    "respon cepat dari seller and sangat sopan orangnya",
    "kualiti lagi bagus kalau banding dengan brand lain ni",
    "app selalu stop sendiri setiap kali i bukak, penat i",
    "i tak recommend barang ni secara direct, jangan beli",
    "berbaloi, harga murah and delivery laju, cemerlang lah",
    "pilihan warna sangat terhad kat sini, tak banyak choice",
    "proses refund berjalan lancar and senang, best lah ni",
    "barang sampai selamat and i sangat puas hati semalam",
    "tracking senang nak follow and selalu ada update baru",
    "customer service bagus, dorang settle masalah i laju",
    "penghantaran cepat walaupun i duduk jauh kat pedalaman",
    "kualiti padan dengan description and harga pun adil",
    "i akan beli lagi dari seller ni di masa depan nanti",
    "barang sampai selamat and pack sangat kemas tadi",
    "kualiti memang padu and harga pun murah gila semalam",
    "seller balas message laju gila petang semalam tadi",
    "delivery person sopan and hantar barang on time tadi",
    "i sangat suggest kedai ni untuk semua orang cuba",
    "barang sebijik macam dalam gambar, tak menipu langsung",
    "proses refund mudah and tak banyak songeh dorang ni",
    "material baju ni sejuk and selesa gila i pakai tadi",
    "app senang nak guna and interface pun cantik sangat",
    "penghantaran pantas and barang dalam keadaan perfect",
    "customer support memang mantap and cepat bantu i tadi",
    "barang luar jangkaan i, memang kualiti terbaik lah ni",
    "packaging tebal and barang selamat sampai rumah i tadi",
    "service cemerlang and staff dorang pun peramah gila",
    "i puas hati gila dengan pembelian kali ni semalam",
    "barang sampai awal dari yang dijanjikan, terbaik lah",
    "warna nampak eksklusif and kualiti memang padu gila",
    "delivery laju gila walaupun tengah musim sale baru ni",
    "item ni ringan and senang nak angkut ke sana sini",
    "proses return mudah and seller sangat membantu i tadi",
    "barang berkualiti tinggi and harga berbaloi sangat-sangat",
    "abang courier sangat peramah and hormat orang tadi",
    "app display kemas and takda bug langsung semalam tadi",
    "item ni tahan lasak and sesuai guna outdoor pagi tadi",
    "respon seller pantas and sangat memudahkan urusan i",
    "barang pack dengan rapi and sampai selamat kat i tadi",
    "kualiti memang gempak and harga pun murah sangat lah",
    "highly recommended untuk siapa yang cari barang murah",
    "barang sampai selamat walaupun hujan lebat kat luar",
    "kualiti solid and finishing dia memang kemas semalam",
    "app selalu update langkah-langkah penghantaran barang ni",
    "pekerja sopan and proses pertukaran barang pun mudah",
    "material selesa and kualiti memang tinggi gila ni",
    "delivery terpantas yang i pernah guna setakat ni saja",
    "barang sebijik macam dalam live stream seller tadi",
    "refund dah masuk balik dalam wallet digital i tadi",
    "barang senang nak maintain and nampak berkilat tadi",
    "pekerja memang efisien and sangat peramah orangnya tadi",
    "tracking barang delivery dah update semalam pagi tadi",
    "kualiti yang memuaskan untuk harga macam ni punya",
    "experience guna app ni memang yang terbaik setakat ni",
    "penghantaran dah sampai kat i and i sangat puas hati",
    "customer help selesaikan masalah i dengan laju tadi",
    "material tebal and tahan lama, memang berbaloi beli ni",
    "delivery express memang betul-betul berfungsi semalam tadi",
    "barang sampai tanpa sebarang calar, terbaik lah ni",
    "quality control dorang memang jaga betul-betul semalam",
    "app takda issue langsung, sangat smooth nak guna ni",
    "pekerja tolong i angkat kotak besar tadi, baik gila",
    "barang sangat senang nak guna, tak faham boleh tanya",
    "delivery tadi memang free, tak bayar satu sen pun",
    "kualiti yang berbaloi and solid gila i rasa semalam",
    "notification app sangat berguna untuk track kerja ni",
    "abang delivery sangat berbudi bahasa masa hantar tadi",
    "barang lagi elok dari apa yang i bayangkan dulu",
    "proses refund memang laju betul i rasa semalam tadi",
    "design simple and functional, i suka seller ni punya",
    "seller reply message i laju sangat tadi, terima kasih",
    "barang sampai dalam keadaan yang sangat baik semalam",
    "kualiti yang boleh dipercayai, takda masalah langsung lah",
    "app berfungsi dengan baik and sangat user friendly lah",
    "pekerja kat sini semua ceria saja masa melayan tadi",
    "semua dah settle and i sangat puas hati dengan data",
    "kualiti kain baju ni memang padu macam butik punya",
    "barang sampai sangat awal, memang laju dorang hantar",
    "seller ni jujur masa buat live stream tadi, terbaik",
    "material memang bagus and i suka pakai semalam tadi",
    "delivery laju and barang selamat sampai semalam tadi",
    "app kadang-kadang lembap sikit, tolong fix issue ni",
    "pekerja kat sini sangat peramah masa i datang tadi",
    "barang ada calar sikit tapi function dia masih okay",
    "recommended seller, korang boleh cari dia kalau nak",
    "proses refund telus and dapat balik sekelip mata saja",
    "warna barang ni sangat cantik, i suka betul semalam",
    "design simple tapi nampak functional and menarik betul",
    "abang delivery polite sangat masa hantar barang tadi",
    "delivery lambat sikit sebab hujan tapi barang selamat",
    "kualiti yang konsisten and memang hebat buat kerja",
    "barang nampak eksklusif and memang yang terbaik lah",
    "display app nampak bersih, terima kasih banyak tadi",
    "pekerja sangat berpengalaman and tahu pasal barang tadi",
    "penghantaran on time macam yang dijanjikan semalam tadi",
    "masalah dah settle dengan bantuan support team tadi",
    "material memang tahan lasak and kualiti memang elok",
    "hantaran laju sangat nanti nak repeat order lagi lah",
    "barang sebijik macam yang diceritakan dalam iklan ni",
    "design barang ni stylish gempak and i suka sangat ni",
    "delivery laju betul masa sale hari tu, memang mantap",
    "barang dihantar dengan penuh berhati-hati tadi pagi",
    "kualiti solid and memang yang terbaik setakat ni saja",
    "display app boleh improve lagi supaya lebih user friendly",
    "pekerja peramah and sanggup tunggu i tadi masa hantar",
    "delivery awal dari abang courier yang baik hati tadi",
    "barang kualiti tinggi and i sangat puas hati semalam",
    "proses refund laju and masuk terus ke dalam akaun",
    "description barang memang perfect and tak tipu semalam",
    "sistem refund senang nak track and takda masalah ni",
    "barang lagi bagus dari apa yang i expect semalam",
    "delivery laju and barang selamat sampai kat tangan ni",
    "barang ada yang hilang tapi seller jujur nak ganti",
    "kualiti rasa eksklusif and i suka sangat semalam tadi",
    "display app bersih and senang i nak cari barang",
    "pekerja sangat berilmu and banyak membantu i tadi",
    "delivery laju walaupun ada barang yang pecah tadi",
    "quality control kena improve sikit part kemas barang",
    "app ringan and tak makan bateri phone i langsung",
    "pekerja ramah and tolong i angkat barang tadi pagi",
    "delivery on time and barang dalam keadaan perfect lah",
    "proses refund laju tapi respon seller lambat sikit",
    "material selesa and kulit rasa sangat lembut semalam",
    "hantar awal and pack sangat kemas, selamat sampai tadi",
    "barang sampai selamat and i sangat puas hati tadi",
    "tracking senang nak monitor and ada update sentiasa",
    "customer service settle masalah i dengan sangat laju",
    "penghantaran pantas walaupun i duduk jauh gila tadi",
    "kualiti sebijik macam description and harga pun adil",
    "i akan beli lagi dari seller ni hari depan nanti",
    "service memuaskan and laju sangat i rasa semalam tadi",
    "semua barang selamat and dibungkus dengan sangat padu",
    "abang rider pun sangat sopan masa hantar barang tadi",
    "i gembira sangat dapat barang ni petang semalam tadi",
    "kualiti memang tak mengecewakan langsung i rasa lah",
    "senang sangat nak guna and memang jimat duit i",
    "proses pembelian yang sangat lancar and takda masalah",
    "barang nampak premium and eksklusif betul i rasa tadi",
    "courier hantar barang sampai depan pintu rumah tadi",
    "i memang sangat syorkan kedai ni kat kawan-kawan",
    "terima kasih seller, barang memang padu and terbaik",
    "feedback sangat pantas and sangat membantu urusan i",
    "packaging memang secure sangat dah i tengok semalam",
    "harga berpatutan and kualiti pun sangat-sangat bagus",
    "barang sampai awal betul dari apa yang i jangka",
    "puas hati sangat and takda complaint satu pun tadi",
    "material kain ni sangat sejuk and selesa i pakai",
    "memang mantap pihak sana buat kerja, i hargai sangat",
    "tiada kerosakan and barang nampak macam baru saja",
    "delivery person call dulu sebelum sampai tadi pagi",
    "proses return tak leceh langsung and sangat mudah lah",
    "i akan repeat order lagi dengan seller ni nanti",
    "barang berkualiti and sangat original i rasa tadi",
    "respon sangat pantas and terbaik dari pihak support",
    "penghantaran yang sangat efisien i rasa semalam",
    "pembungkusan rapi and barang tidak pecah masa sampai",
    "semuanya dalam keadaan yang elok and i sangat suka",
    "item ni sangat berguna masa i guna semalam tadi",
    "puas hati sangat dengan hasil kerja dorang kat sini",
    "service mantap and abang rider pun ramah betul tadi",
    "kualiti barang ni memang tiptop and terbaik sekali lah",
    "harga paling murah yang i pernah jumpa setakat ni",
    "barang sebijik macam yang i tengok dalam iklan tadi",
    "senang nak pasang and guna, tak payah pening kepala",
    "pembelian terbaik untuk i pada bulan ni punya order",
    "item nampak cantik sangat-sangat lah i rasa tadi",
    "penghantaran yang sangat laju lah dari pihak courier",
    "kualiti gempak and harga pun sangat berpatutan tadi",
    "memang puas hati sangat i rasa semalam tadi pagi",
    "takda barang yang kurang masa i check tadi pagi",
    "semuanya berfungsi dengan sangat cemerlang and baik lah",
    "customer service pun reply laju betul masa i tanya",
    "barang dibungkus dengan sangat selamat and rapi tadi",
    "i suka sangat kualiti item ni, memang terbaik lah",
    "proses refund pun sangat mudah and takda masalah tadi",
    "abang courier sangat sopan masa hantar barang tadi",
    "i suggest korang beli kat sini kalau nak barang elok",
    "barang sampai tepat pada masanya macam yang dijanjikan",
    "kualiti memang elok and memuaskan hati i tadi pagi",
    "harga berbaloi and kualiti padu betul i rasa",
    "mantap seller ni lah, nanti i beli lagi",
    "kualiti barang memang terbaik, tak nampak macam murah",
    "delivery pantas sangat, i impress dengan speed dorang",
    "app ni cantik tapi kadang-kadang dia hang kejap",
    "barang sampai tadi, kotak kemas and safe betul",
    "customer support laju betul reply masa i tanya",
    "i suggest korang beli kat sini kalau nak barang elok",
    "service kat sini memang mantap, tak rugi i beli",
    "service memang mantap, rider pun peramah tadi",
    "barang sebijik macam dalam iklan, tak menipu langsung",
    "senang nak guna and interface pun cantik sangat lah",
    "pembelian terbaik untuk bulan ni, i sangat happy",
    "item nampak premium and memang eksklusif i rasa tadi",
    "penghantaran yang efisien betul i rasa semalam",
    "kualiti barang ni tiptop and terbaik sekali lah",
    "abang courier sangat sopan masa hantar barang tadi",
    "i memang recommend kedai ni kat kawan i nanti",
    "terima kasih seller barang padu and sangat berkualiti",
    "feedback pantas and sangat membantu urusan i tadi",
    "packaging secure sangat dah i tengok semalam",
    "harga patut kualiti pun sangat tinggi dorang bagi",
    "barang sampai awal betul dari apa yang i jangka",
    "puas hati sangat and takda complaint satu pun tadi",
    "material kain ni sangat sejuk and selesa i pakai",
    "memang mantap pihak sana buat kerja i hargai sangat",
    "tiada kerosakan and barang nampak macam baru saja tahu",
    "delivery person call dulu sebelum sampai tadi pagi",
    "proses return tak leceh langsung and sangat mudah lah",
    "i akan repeat order lagi dengan seller ni nanti",
    "barang berkualiti and sangat original i rasa tadi",
    "respon sangat pantas and terbaik dari pihak support",
    "warna dia cantik betul, sebijik macam dalam gambar",
    "pembungkusan rapi and barang tidak pecah masa sampai",
    "semuanya dalam keadaan yang elok and i sangat suka",
    "item ni sangat berguna masa i guna semalam tadi",
    "puas hati sangat dengan hasil kerja dorang kat sini",
    "service mantap and abang rider pun ramah betul tadi",
    "seller peramah and jujur, i suka cara dia handle",
    "harga paling murah yang i pernah jumpa setakat ni",
    "barang sebijik macam yang i tengok dalam iklan tadi",
    "senang nak pasang and guna tak payah pening kepala",
    "pembelian terbaik untuk i pada bulan ni punya order",
    "item nampak cantik sangat-sangat lah i rasa tadi",
    "penghantaran yang sangat laju lah dari pihak courier",
    "kualiti gempak and harga pun sangat berpatutan tadi",
    "memang puas hati i rasa semalam tadi pagi",
    "takda barang yang kurang masa i check tadi pagi",
    "semuanya berfungsi dengan sangat cemerlang and baik lah",
    "customer service pun reply laju betul masa i tanya",
    "barang dibungkus dengan sangat selamat and rapi tadi",
    "i suka kualiti item ni memang terbaik lah",
    "proses refund pun sangat mudah and takda masalah tadi",
    "abang courier sangat sopan masa hantar barang tadi",
    "i suggest kurang beli kat sini kalau nak barang elok",
    "barang sampai tepat pada masanya macam yang dijanjikan",
    "kualiti memang elok and memuaskan hati i tadi pagi",
    "kualiti kain ni lembut, selesa i pakai pergi kerja",
    "memang mantap seller ni lah nanti i beli lagi",
    "service courier sangat bagus hantar sampai ke pintu",
    "kualiti memang tiada tandingan dengan harga murah ni",
    "i sangat berpuas hati dengan barangan yang diterima",
    "proses order sangat mudah and cepat dorang proses",
    "item sampai dalam keadaan yang cantik betul",
    "memang terbaik lah seller ni buat kerja dengan jujur",
    "i akan rekomen kedai ni pada family and member",
    "terima kasih banyak seller barang memang mantap",
    "kualiti kain sejuk and selesa sangat bila pakai tadi",
    "i tak sangka barang sampai cepat sangat macam ni",
    "puas hati sangat dengan service dorang semalam",
    "barang ni berkualiti tinggi and sangat berbaloi beli",
    "i rasa ni pembelian paling berbaloi i pernah buat",
    "service dari team support mengagumkan betul lah",
    "packaging dia kemas and nampak profesional betul",
    "delivery laju and abang rider pun peramah sangat tadi",
    "i suka sangat design barang ni nampak sangat moden",
    "kualiti memang mantap and i akan repeat order lagi",
    "terbaik lah seller ni respon laju and sangat membantu",
    "barang sampai selamat and tiada sebarang kesan calar",
    "i rasa happy sangat dapat barang yang berkualiti camni",
    "penghantaran pantas sangat i tak sangka sekejap je sampai",
    "berbaloi sangat beli kat sini kualiti gred a",
    "i sangat suka dengan feature yang ada pada barang ni",
    "proses bayaran sangat lancar and takda error langsung",
    "item nampak eksklusif and nampak mahal betul i rasa",
    "service mantap betul i sangat puas hati tadi",
    "barang sampai awal and abang delivery pun sangat baik",
    "i recommend sangat kedai ni untuk semua orang cuba",
    "kualiti barang memang tiptop and i tak menyesal beli",
    "respon dari seller sangat bagus and sangat profesional",
    "penghantaran yang pantas betul i rasa semalam",
    "barang dibungkus dengan tebal bubble wrap memang selamat",
    "i sangat berpuas hati dengan kualiti barang tadi pagi",
    "memang mantap lah seller ni jaga kualiti barang betul",
    "i akan beli lagi dari seller ni sebab service dia best",
    "kualiti gempak and harga pun sangat murah lah",
    "i gembira sangat dapat barang yang i nak ni",
    "proses pertukaran barang pun sangat mudah and cepat",
    "barang sampai dalam keadaan yang baik sekali",
    "i suggest korang semua beli barangan dari seller ni",
    "kualiti memang memuaskan and i sangat happy hari ni",
    "service delivery memang terbaik and dorang buat kerja laju",
    "i takkan ragu-ragu untuk beli lagi kat kedai ni",
    "barang memang sebijik macam gambar and kualiti mantap",
    "terbaik lah service kat sini memang i puji betul",
    "barang sampai tadi and kualiti memang memuaskan sangat",
    "i sangat suka dengan bungkusan yang kemas and rapi",
    "memang berbaloi dengan apa yang i bayar semalam",
    "respon seller memang terbaik and sangat membantu i tadi",
    "penghantaran laju sangat i impress sangat dengan seller ni",
    "kualiti barang padu betul and i rasa ni paling best",
]

# ========================================================
# STEP 2: NORMALIZATION (DONE EARLY)
# ========================================================

def normalize(text):
    text = text.lower()
    text = re.sub(r"[^a-z0-9\s]", "", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text

texts = [normalize(t) for t in texts]

# ========================================================
# STEP 3: GENERATE AUDIO (Edge TTS + variation)
# ========================================================

voices = ["ms-MY-OsmanNeural", "ms-MY-YasminNeural"]
rates = ["-10%", "+0%", "+10%"]

audio_dir = "dataset/audio"
os.makedirs(audio_dir, exist_ok=True)

async def generate_audio():
    metadata = []

    for i, text in enumerate(texts):
        voice = random.choice(voices)
        rate = random.choice(rates)

        filename = f"{i}.wav"
        filepath = os.path.join(audio_dir, filename)

        retries = 5  # Number of retries
        success = False
        for attempt in range(retries):
            try:
                tts = edge_tts.Communicate(text, voice=voice, rate=rate)
                await tts.save(filepath)
                success = True
                break  # Exit retry loop if successful
            except Exception as e: # Catch broader exceptions for resilience
                print(f"Attempt {attempt + 1}/{retries} failed for text '{text[:50]}...': {e}")
                if attempt < retries - 1:
                    await asyncio.sleep(5)  # Wait 5 seconds before retrying
                else:
                    print(f"Failed to generate audio for text '{text}' after {retries} attempts. Skipping.")

        if success: # Only process if audio was successfully generated
            # resample to 16kHz mono
            audio = AudioSegment.from_file(filepath)
            audio = audio.set_frame_rate(16000).set_channels(1)
            audio.export(filepath, format="wav")

            metadata.append({"audio": filepath, "text": text})

    return metadata

metadata = asyncio.run(generate_audio())

# ========================================================
# STEP 4: LOAD DATASET
# ========================================================

dataset = Dataset.from_list(metadata)
dataset = dataset.cast_column("audio", Audio(sampling_rate=16000))

# ========================================================
# STEP 5: PRECOMPUTE INPUT_FEATURES + LABELS
# ========================================================

processor = AutoProcessor.from_pretrained("openai/whisper-small")

def prepare(batch):
    audio = batch["audio"]

    inputs = processor(
        audio["array"],
        sampling_rate=audio["sampling_rate"]
    )

    input_features = inputs.input_features[0]
    labels = processor.tokenizer(batch["text"]).input_ids

    return {
        "input_features": input_features,
        "labels": labels
    }

dataset = dataset.map(prepare, remove_columns=["audio", "text"])

# ========================================================
# STEP 6: SAVE FINAL TRAIN-READY DATASET
# ========================================================

output_dataset_name = "whisper_bilingual_feedback_ready"
dataset.save_to_disk(output_dataset_name)

print("Dataset ready. Contains precomputed input_features and labels.")

# Zip the dataset for download
zip_filename = f"{output_dataset_name}.zip"
shutil.make_archive(output_dataset_name, "zip", output_dataset_name)
print(f"Dataset zipped to {zip_filename}")
